title:              Gabriela Filipkowska
email:              
description:        research and game development - personal blog
author:             Gabriela Filipkowska
baseurl:            ""
url:                "https://gfilipkowska.github.io/"

# Social Profiles
twitter_username:   
github_username:   gfilipkowska
facebook_username:  
instagram_username:  xonty.indiegames
linkedin_username:  

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

